[project]
authors = [{ name = "lxl66566", email = "lxl66566@gmail.com" }]
name = "ecust-electricity-statistics"
version = "1.2.0"
description = "华东理工大学（华理）电费统计"
license = "MIT"
readme = "README.md"
dependencies = ["requests>=2"]
requires-python = ">=3.12"
